KicksTV/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from .forms import UserProfileRegistrationForm

from . import views
import gallery
import kickstvDropbox
import blog
import userProfile




urlpatterns = [
    # Home Page Url
    url(r'^$', views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    
    # Dropbox Urls
    url(r'^dropbox/', include('kickstvDropbox.urls', namespace='dropbox')),
    
    # Blog Urls
    url(r'^(?P<user>[\w-]+)/blog/', include('blog.urls', namespace='blogs')),
    
    # UserProfile Urls
    url(r'^(?P<user>[\w-]+)/profile/', include('userProfile.urls', namespace='profile')),
    
    # Gallery Urls
    url(r'^(?P<gallery_user>[\w-]+)/gallery/', include('gallery.urls', namespace='gallerys')),
    url(r'^featured/gallerys$', gallery.views.featuredGallery, name='featured-gallery'),
    url(r'^search/gallerys', gallery.views.searchGallery, name='search-gallery'),
	url(r'^search/gallery/result$', gallery.views.GallerySearchListView.as_view(), name='gallery-search-list-view'),

    # Custom Registration Redux Registration 
    url(r'^accounts/register$', views.MyRegistrationView.as_view(), name="registration_register"),

    # Registration Redux Urls
    url(r'^accounts/', include('registration.backends.default.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    
    url(r'^view/(?P<slug>[\w-]+)/$', views.projectDetailView, name="project-detail"),
    url(r'^add/$', views.projectAddView, name="project-add"),
    url(r'^view/(?P<slug>[\w-]+)/delete/$', views.projectDeleteView, name="project-delete"),
    url(r'^view/(?P<slug>[\w-]+)/edit/$', views.projectEditView, name="project-edit"),


    url(r'^view/(?P<slug>[\w-]+)/post/(?P<post_id>[0-9]+)/$', views.blogDetailView, name="post-detail"),
    url(r'^view/(?P<slug>[\w-]+)/post/add/$', views.blogAddView, name="post-add"),
    url(r'^view/(?P<slug>[\w-]+)/post/(?P<post_id>[0-9]+)/delete/$', views.blogDeleteView, name="post-delete"),
    url(r'^view/(?P<slug>[\w-]+)/post/(?P<post_id>[0-9]+)/edit/$', views.blogEditView, name="post-edit"),
]

gallery/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.userGalleryView, name="user-gallery"),
	url(r'^view/(?P<slug>[\w-]+)/$', views.userDetailView, name="user-gallery-detail"),
	
	url(r'^add/$', views.galleryCreate, name="gallery-add"),
	url(r'^(?P<slug>[\w-]+)/update$', views.galleryUpdate, name="gallery-update"),
	url(r'^(?P<slug>[\w-]+)/delete/$', views.galleryDelete, name="gallery-delete"),
	url(r'^(?P<slug>[\w-]+)/favorite/$', views.galleryFavorite, name="favorite"),

	url(r'^(?P<slug>[\w-]+)/image/add/$', views.imageCreate, name='image-add'),
	url(r'^(?P<slug>[\w-]+)/delete/image/(?P<image_id>[0-9]+)/$', views.imageDelete, name='image-delete'),
	

	]

userProfile/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from . import views

urlpatterns = [
	url(r'^$', views.userProfile, name="index"),
	url(r'^settings/', views.userProfileSettings, name="user-settings"),
	]

userProfile/models.py
from __future__ import unicode_literals

from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.files import File as FileWrapper

from django.shortcuts import get_object_or_404

from django.contrib.auth.models import User

def upload_location(instance, filename):
    return "profile_images/%s/%s" %(instance.user.username, filename)


class Profile(models.Model):
	user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, primary_key=True)
	profile_image = models.ImageField(
		upload_to=upload_location,
		height_field="height_field",
		width_field="width_field",
	)
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	bio = models.TextField(max_length=500, blank=True)
	location = models.CharField(max_length=30, blank=True)

	def __str__(self):
		return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        p = Profile(user=instance)
        p.save()

userProfile/forms.py
from django import forms

from django.contrib.auth.models import User

from .models import Profile

class ProfileSettings(forms.ModelForm):

	firstName = forms.CharField(label=(u'First Name'), help_text='Not required', max_length=30, required=False)
	lastName = forms.CharField(label=(u'Last Name'), help_text='Not required', max_length=30, required=False)

	class Meta:
		model = Profile
		fields = ['firstName', 'lastName', 'profile_image', 'bio', 'location']

userProfile/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse

from django.utils.datastructures import MultiValueDictKeyError

from django.core.urlresolvers import reverse
from django.contrib import messages

from django.contrib.auth.models import User, Group

from .models import Profile
from .forms import ProfileSettings

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

# Create your views here.


def userProfile(request, user):
	user = get_object_or_404(User, username=user)
	
	if user.profile:
		context = {
			'user': user,
		}
		return render(request, 'userProfile/index.html', context)
	else:
		return render(request, 'default-form.html')

def userProfileSettings(request, user):
	if not request.user.username == user:
		return HttpResponse('<h1>Cannot edit other uses settings</h1>')
	else:
		user = get_object_or_404(User, username=user)
		form = ProfileSettings(request.POST or None, request.FILES or None, instance=user.profile)
		if form.is_valid():

			user.first_name = form.cleaned_data['firstName']
			user.last_name = form.cleaned_data['lastName']
			profile = form.save(commit=False)
			profile.user = user

			try:
				profile.profile_image = request.FILES['profile_image']
				file_type = profile.profile_image.url.split('.')[-1]
				file_type = file_type.lower()
				if file_type not in IMAGE_FILE_TYPES:
					context = {
						'profile': profile,
						'form': form,
						'error_message': 'Image file must be PNG, JPG or JPEG!',
					}
					return render(request, 'default-form.html', context)
			except MultiValueDictKeyError:
				profile.profile_image = profile.profile_image

			profile.save()
			user.save()
			messages.success(request, "Successfully Made Changes!")
			return HttpResponseRedirect(reverse('profile:index', args=[user]))
		context = {
			'formTitle': 'Profile Settings',
			'form': form,
		}

		return render(request, 'default-form.html', context)

templates/userProfile/base.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% load staticfiles %}

{% block content %}
	<div class="container-fluid" style="margin-top: 50px">
		<div class="row" style="background-color: #f2f3f4;padding-top: 20px;">
			<div class="col-md-12">
				<div class="col-md-2 col-sm-3 col-xs-5 col-xs-offset-1">
					<div class="thumbnail">
						{% if user.profile.profile_image %}
							<img src="{{ user.profile.profile_image.url }}">
							{% else %}
								<img src="{% static 'img/default-profile-image.png' %}">
						{% endif %}
					</div>
				</div>
				<div class="col-md-5 col-sm-8 col-sm-offset-0 col-xs-11 col-xs-offset-1">
					<h3 class="obj-title">{{ user.username|title }}</h3>
					<p class="obj-default">{{ user.first_name }} {{ user.last_name }}</p>
					<p class="obj-default">{{ user.profile.location }}</p>
					<p class="obj-default">{{ user.email }}</p>
					<p class="obj-date">{{ user.date_joined|date:"Y/M" }}</p>
					<p class="obj-desc">{{ user.profile.bio }}</p>
				</div>


				<div class="col-md-4 col-md-offset-8 col-sm-5 col-sm-offset-7 col-xs-10" style="margin-top: 30px;">
					<div class="bs-example" data-example-id="nav-tabs-with-dropdown">
						<ul class="nav nav-tabs">
							<li role="presentation" class="{% block home_active %}{% endblock %}">
								<a href="{% url 'profile:index' user %}">Home</a>
							</li>
							<li role="presentation" class="{% block gallery_active %}{% endblock %}">
								<a href="{% url 'gallerys:user-gallery' user %}">Gallery</a>
							</li>
							{% if user.project_set.all %}
								<li role="presentation" class="{% block blog_active %}{% endblock %}">
									<a href="{% url 'blogs:index' user %}">Blog</a>
								</li>
								{% else %}
									<li role="presentation" class="disabled">
										<a>Blog</a>
									</li>
							{% endif %}
							{% if request.user == user %}
								<li role="presentation" class="dropdown">
									<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
										<span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
										<span class="caret"></span>
									</a>
									<ul class="dropdown-menu">
										<li>
											<a href="{% url 'profile:user-settings' user %}">Profile Settings</a>
										</li>
										<li>
											<a href="{% url 'auth_password_change' %}">Change Password</a>
										</li>
									</ul>
								</li>
							{% endif %}
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	{% block profile_content %}

	{% endblock %}

{% endblock %}

templates/userProfile/index.html
{% extends 'userProfile/base.html' %}
{% block title %}{{ user.username|title }} Profile{% endblock %}
{% block home_active %}active{% endblock %}

{% block profile_content %}
	<div class="container">
		<h1>Home Page</h1>
	</div>
{% endblock %}