KicksTV/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from .forms import UserProfileRegistrationForm

from . import views
import gallery
import kickstvDropbox
import blog
import userProfile




urlpatterns = [
    # Home Page Url
    url(r'^$', views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    
    # Dropbox Urls
    url(r'^dropbox/', include('kickstvDropbox.urls', namespace='dropbox')),
    
    # Blog Urls
    url(r'^(?P<user>[\w-]+)/blog/', include('blog.urls', namespace='blogs')),
    
    # UserProfile Urls
    url(r'^(?P<user>[\w-]+)/profile/', include('userProfile.urls', namespace='profile')),
    
    # Gallery Urls
    url(r'^(?P<gallery_user>[\w-]+)/gallery/', include('gallery.urls', namespace='gallerys')),
    url(r'^featured/gallerys$', gallery.views.featuredGallery, name='featured-gallery'),
    url(r'^search/gallerys', gallery.views.searchGallery, name='search-gallery'),
	url(r'^search/gallery/result$', gallery.views.GallerySearchListView.as_view(), name='gallery-search-list-view'),

    # Custom Registration Redux Registration 
    url(r'^accounts/register$', views.MyRegistrationView.as_view(), name="registration_register"),

    # Registration Redux Urls
    url(r'^accounts/', include('registration.backends.default.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    
    url(r'^view/(?P<slug>[\w-]+)/$', views.projectDetailView, name="project-detail"),
    url(r'^add/$', views.projectAddView, name="project-add"),
    url(r'^view/(?P<slug>[\w-]+)/delete/$', views.projectDeleteView, name="project-delete"),
    url(r'^view/(?P<slug>[\w-]+)/edit/$', views.projectEditView, name="project-edit"),


    url(r'^view/(?P<slug>[\w-]+)/post/(?P<post_id>[0-9]+)/$', views.blogDetailView, name="post-detail"),
    url(r'^view/(?P<slug>[\w-]+)/post/add/$', views.blogAddView, name="post-add"),
    url(r'^view/(?P<slug>[\w-]+)/post/(?P<post_id>[0-9]+)/delete/$', views.blogDeleteView, name="post-delete"),
    url(r'^view/(?P<slug>[\w-]+)/post/(?P<post_id>[0-9]+)/edit/$', views.blogEditView, name="post-edit"),
]

gallery/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.userGalleryView, name="user-gallery"),
	url(r'^view/(?P<slug>[\w-]+)/$', views.userDetailView, name="user-gallery-detail"),
	
	url(r'^add/$', views.galleryCreate, name="gallery-add"),
	url(r'^(?P<slug>[\w-]+)/update$', views.galleryUpdate, name="gallery-update"),
	url(r'^(?P<slug>[\w-]+)/delete/$', views.galleryDelete, name="gallery-delete"),
	url(r'^(?P<slug>[\w-]+)/favorite/$', views.galleryFavorite, name="favorite"),

	url(r'^(?P<slug>[\w-]+)/image/add/$', views.imageCreate, name='image-add'),
	url(r'^(?P<slug>[\w-]+)/delete/image/(?P<image_id>[0-9]+)/$', views.imageDelete, name='image-delete'),
	

	]

gallery/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import Permission, User
from django.db import models
from django.core.urlresolvers import reverse
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.shortcuts import get_object_or_404

from django.utils.text import slugify


import os
import sys
import shutil

 
# Create your models here.
def upload_location(instance, filename):
    folder = instance.slug.replace("_", "/")
    return "gallery_images/%s/%s" %(folder, filename)

class Gallery(models.Model):
    user = models.ForeignKey(User, default=1)
    gallery_title = models.CharField(max_length=25)
    gallery_date = models.DateField(null=False, blank=False)
    gallery_image = models.ImageField(
        upload_to=upload_location, 
        null=False, 
        blank=False,
        height_field="height_field",
        width_field="width_field",
        )
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    slug = models.SlugField(max_length=40, unique=True)
    gallery_description = models.CharField(max_length=70)
    is_favorite = models.BooleanField(default=False)
    is_homepage_gallery = models.BooleanField(default=False)

    def __unicode__(self):
        return self.gallery_title

    def __str__(self):
        return self.gallery_title

    def get_absolute_url(self):
        return reverse("gallerys:user-gallery-detail", kwargs={
            "slug": self.slug,
            "gallery_user": self.user,
            })

class Image(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    image_title = models.CharField(max_length=25)
    image_image = models.ImageField(
        upload_to=upload_location,
        height_field="height_field",
        width_field="width_field",
        )
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    slug = models.SlugField(max_length=40)

    def __unicode__(self):
        return self.image_title

    def __str__(self):
        return self.image_title



# Creating slugs before saving
def create_slug(instance, new_slug=None):
    slug = "%s_%s" %(instance.user, slugify(instance.gallery_title))
    if new_slug is not None:
        slug = new_slug
    qs = Gallery.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s_%s-%s" %(instance.user, slugify(instance.gallery_title),qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_gallery_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    elif not instance.slug == slugify(instance.user) + "" + slugify(instance.gallery_title): 
        instance.slug = create_slug(instance)

def pre_save_image_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        gallery = Gallery.objects.get(id=instance.gallery.id)
        instance.slug = "%s_%s" %(gallery.user,slugify(gallery.gallery_title))


# These two auto-delete files from filesystem when they are unneeded:

@receiver(models.signals.post_delete, sender=Gallery)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.gallery_image:
        if os.path.isfile(instance.gallery_image.path):
            os.remove(instance.gallery_image.path)
            try:
                folder = instance.gallery_image.path.rsplit('/', 1)
                shutil.rmtree(folder[0])
            except OSError, e:
                print("Error: %s - %s." % (e.filename, e.strerror))


def auto_delete_file_on_change(sender, instance, *args, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        print("instance.pk is null")
        return

    if instance.gallery_title:
        old_gallery = get_object_or_404(Gallery, id=instance.pk)
        if instance.gallery_title == old_gallery.gallery_title:
            return

    gallery_path = str(instance.gallery_image).split("/")
    old_file = gallery_path[1] + "/" + gallery_path[2]
    new_file = instance.slug.replace("_", "/")
    
    if not old_file == new_file:
        folder_path_to_change = str(instance.gallery_image.path).rsplit('/', 1)
        folder_path = str(instance.gallery_image.path).rsplit('/', 2)
        new_folder_name = str(new_file).rsplit('/', 1)
        os.rename(folder_path_to_change[0], folder_path[0] + "/" + new_folder_name[1])
        instance.gallery_image = gallery_path[0] + "/" + gallery_path[1] + "/" + new_folder_name[1] + "/" + gallery_path[3]

        all_images = Image.objects.filter(gallery=instance)
        if all_images:
            for image in all_images:
                if not os.path.isfile(image.image_image.path):
                    image_path = str(image.image_image).split("/")
                    print(image_path[0] + "/" + image_path[1] + "/" + new_folder_name[1] + "/" + image_path[3])
                    image.image_image = image_path[0] + "/" + image_path[1] + "/" + new_folder_name[1] + "/" + image_path[3]
                    image.save()


pre_save.connect(pre_save_gallery_receiver, sender=Gallery)
pre_save.connect(pre_save_image_receiver, sender=Image)
pre_save.connect(auto_delete_file_on_change, sender=Gallery)

gallery/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Gallery, Image


class GalleryForm(forms.ModelForm):

    class Meta:
        model = Gallery
        fields = ['gallery_title', 'gallery_date', 'gallery_image', 'gallery_description']

class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = ['image_title', 'image_image']

gallery/views.py
import operator
from django.views.generic import ListView
from django.contrib.postgres.search import SearchQuery, SearchRank, SearchVector
from django.views import generic
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils.datastructures import MultiValueDictKeyError
from django.contrib.auth.models import User, Group
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import GalleryForm, ImageForm
from .models import Gallery, Image, User

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

# Create your views here.

def userGalleryView(request, gallery_user):
	gallery_user = get_object_or_404(User, username=gallery_user)
	all_gallery = Gallery.objects.filter(user=gallery_user).order_by("-gallery_date")

	paginator = Paginator(all_gallery, 9)
	page = request.GET.get('page')
	try:
		gallery = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		gallery = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		gallery = paginator.page(paginator.num_pages)
	
	return render(request, 'gallery/index.html', {
		'all_gallery': gallery,
		'user': gallery_user,
		})
			



def userDetailView(request, gallery_user, slug):
	user = get_object_or_404(User, username=gallery_user)
	gallery = get_object_or_404(Gallery, slug=slug)
	
	context = {
		'user': user,
		'gallery': gallery,
	}
	return render(request, 'gallery/gallery_detail.html', context)




def galleryCreate(request, gallery_user):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/accounts/login')
	else:
		form = GalleryForm(request.POST or None, request.FILES or None)
		if form.is_valid():
		    gallery = form.save(commit=False)
		    gallery.user = request.user
		    gallery.gallery_image = request.FILES['gallery_image']
		    file_type = gallery.gallery_image.url.split('.')[-1]
		    file_type = file_type.lower()
		    if file_type not in IMAGE_FILE_TYPES:
		        context = {
		            'formTitle': 'Create Gallery',
		            'gallery': gallery,
		            'form': form,
		            'error_message': 'Image file must be PNG, JPG, or JPEG',
		        }
		        return render(request, 'default-form.html', context)
		    gallery.save()
		    messages.success(request, "Successfully Created!")
		    return HttpResponseRedirect(gallery.get_absolute_url())
		context = {
		    'formTitle': 'Create Gallery',
		    'form': form,
		}
		return render(request, 'default-form.html', context)

def galleryUpdate(request, gallery_user, slug):
	gallery = get_object_or_404(Gallery, slug=slug)
	form = GalleryForm(request.POST or None, instance=gallery)
	if form.is_valid():
		gallery = form.save(commit=False)
		try:
			gallery.gallery_image = request.FILES['gallery_image']
			file_type = gallery.gallery_image.url.split('.')[-1]
			file_type = file_type.lower()
			if file_type not in IMAGE_FILE_TYPES:
				context = {
					'formTitle': 'Update Gallery',
					'gallery': gallery,
					'form': form,
					'error_message': 'Image file must be PNG, JPG, or JPEG',
					}
				return render(request, 'default-form.html', context)
		except MultiValueDictKeyError:
			gallery.gallery_image = gallery.gallery_image

		form.save()
		messages.success(request, "Successfully Editted!")
		return HttpResponseRedirect(gallery.get_absolute_url())
	context = {
		'formTitle': 'Update Gallery',
		'form': form,
	}
	return render(request, 'default-form.html', context)

def galleryDelete(request, gallery_user, slug):
	gallery = get_object_or_404(Gallery, slug=slug)
	gallery.delete()
	messages.error(request, "Successfully Deleted!")
	return HttpResponseRedirect(reverse('gallerys:user-gallery', args=[gallery_user]))


def imageCreate(request, gallery_user, slug):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/accounts/login')
	else:
		form = ImageForm(request.POST or None, request.FILES or None)
		gallery = get_object_or_404(Gallery, slug=slug)
		if form.is_valid():
		    image = form.save(commit=False)
		    image.gallery = gallery
		   
		    image.image_image = request.FILES['image_image']
		    file_type = gallery.gallery_image.url.split('.')[-1]
		    file_type = file_type.lower()
		    if file_type not in IMAGE_FILE_TYPES:
		        context = {
		            'formTitle': 'Add Image',
		            'image': image,
		            'form': form,
		            'error_message': 'Image file must be PNG, JPG, or JPEG',
		        }
		        return render(request, 'default-form.html', context)
		    image.save()
		    messages.success(request, "Successfully Added!")
		    return HttpResponseRedirect(gallery.get_absolute_url())
		context = {
		    'formTitle': 'Add Image',
		    "form": form,
		}
		return render(request, 'default-form.html', context)


def imageDelete(request, gallery_user, slug, image_id):
	gallery = get_object_or_404(Gallery, slug=slug)
	image = get_object_or_404(Image, pk=image_id)
	image.delete()
	messages.error(request, "Successfully Deleted!")
	return HttpResponseRedirect(gallery.get_absolute_url())

def featuredGallery(request):
	all_gallery = Gallery.objects.filter(is_favorite=True)
	if all_gallery:
		paginator = Paginator(all_gallery, 9)
		page = request.GET.get('page')
		try:
			gallery = paginator.page(page)
		except PageNotAnInteger:
			# If page is not an integer, deliver first page.
			gallery = paginator.page(1)
		except EmptyPage:
			# If page is out of range (e.g. 9999), deliver last page of results.
			gallery = paginator.page(paginator.num_pages)


		return render(request, 'gallery/featured.html', {'all_gallery': gallery})
	else:
		return render(request, 'gallery/noFeatured.html')


def galleryFavorite(request, gallery_user, slug):
	all_gallery = Gallery.objects.all()
	gallery = get_object_or_404(Gallery, slug=slug)
	try:
		if gallery.is_favorite:
			gallery.is_favorite = False
		else:
			gallery.is_favorite = True

		gallery.save()
	except (KeyError, Gallery.DoesNotExist):
		return HttpResponse("<h1>Gallery Does Not Exist!</h1>")
	else:
		messages.success(request, "Successfully Featured!")
		return HttpResponseRedirect(reverse('featured-gallery'))

def searchGallery(request):
	return render(request, 'gallery/search-gallery.html')


class GallerySearchListView(ListView):
    model = Gallery
    template_name = 'gallery/search-gallery.html'
    paginate_by = 10

    def get_queryset(self):
        all_gallery = Gallery.objects.all()
        keywords = self.request.GET.get('q')
        if keywords:
            query = SearchQuery(keywords)
            vectors = SearchVector('gallery_title')
            all_gallery = all_gallery.annotate(search=vectors).filter(search=query)
        return all_gallery

templates/gallery/detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Gallery Images{% endblock %}
{% block gallery_active %}active{% endblock %}

{% block content %}
	<div id="grey-overlay"></div> 
	<div id="detailImageContainer" class="col-md-12 col-sm-12 col-xs-12">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-offset-1 col-xs-10">
				<div class="thumbnail" id="imageDetailThumbnail" style="height: auto;">
					<div class="btn btn-default btn-xs hidden-sm hidden-md hidden-lg" onclick="closeImage();" href=""><span class="glyphicon glyphicon-remove"></span></div>
					<div class="btn btn-default hidden-xs" onclick="closeImage();" href=""><span class="glyphicon glyphicon-remove"></span></div>
					<img style="opacity: 1;" id="imgContainer" src="">
					<div class="caption">
						<a class="deleteButton" href="">
							<div class="btn btn-default btn-xs hidden-sm hidden-md hidden-lg">
								<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
							</div>
						</a>
						<a class="deleteButton" href="">
							<div class="btn btn-default hidden-xs">
								<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
							</div>
						</a>
						<h2 id="imgContainerTitle"></h2>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12 col-sm-4 col-md-3">
				<div class="panel panel-default" style="padding-right: 0;padding-left: 0; margin-right: 0; margin-right: 0;">
					<div class="panel-heading" style="padding: 0 0 0 15px;">
						{% if gallery %}
							<h3 class="panel-title" style="display: inline-block;">{{ gallery.gallery_title }}</h3>
						
						<div class="btn-group panel-btn-group">
							<a>
								<button class="btn btn-default panel-btn" onClick='confirmDelete("{{ gallery.gallery_title }}")'>
									<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
								</button>
							</a>
							<a href="{% url 'gallerys:gallery-update' gallery.slug %}">
								<button class="btn btn-default panel-btn">
									<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
								</button>
							</a>
							{% if user.is_superuser %}
								{% if gallery.is_favorite %}
									<a href="{% url 'gallerys:favorite' gallery.slug %}">
										<button class="btn btn-default panel-btn">
											<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
										</button>
									</a>
								{% else %}
									<a href="{% url 'gallerys:favorite' gallery.slug %}">
										<button class="btn btn-default panel-btn">
											<span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
										</button>
									</a>
								{% endif %}
							{% endif %}
						</div>
						{% else %}
							<h3 class="panel-title" style="display: inline-block;">Gallery not found</h3>
						{% endif %}
					</div>
					<div class="panel-body">
						<div class="col-md-12">
							{% if gallery %}
								<div class="thumbnail">
								 	<img style="height: auto;" src="{{ gallery.gallery_image.url }}" alt="...">
								 	<div class="caption">
						        		<h3>{{ gallery.gallery_title }}</h3>
						        		<p>{{ gallery.gallery_date }}</p>
						        		<p>{{ gallery.gallery_description }}</p>
						      		</div>
						      	</div>
								{% else %}
									<h3>No gallery!</h3>
							{% endif %}
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-9 col-sm-8 col-xs-12">
				<div class="panel panel-default" style="padding-right: 0;padding-left: 0; margin-right: 0; margin-right: 0;">
					<div class="panel-heading" style="padding: 0 0 0 15px;">
						<h3 class="panel-title" style="display: inline-block;">Images</h3>
						<div class="btn-group panel-btn-group">
							{% if gallery.user == request.user %}
								{% if gallery %}
									<div>
										<a href="{% url 'gallerys:image-add' gallery.slug %}">
											<button class="btn btn-default panel-btn">
												<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
											</button>
										</a>
									</div>
								{% endif %}
							{% endif %}
						</div>
					</div>
					<div class="panel-body">
						{% if gallery.image_set.all %}
							<div class="row row-fix">
							{% for image in gallery.image_set.all %}
								<div class="col-xs-6 col-sm-6 col-md-6">
									<div onclick='viewImage(this, "{{ image.image_title }}"); deleteButton("{{ image.id }}", "{{ gallery.slug }}");' class="thumbnail">
								 		<img class="detailimg" src="{{ image.image_image.url }}" alt="..." style="width: auto;">
							      	</div>
								</div>
								{% cycle "" "</div><div class='row row-fix'>" %}
							{% endfor %}
						{% else %}
							<h3>No images added yet!</h3>
						{% endif %}
					</div>
				</div>
			
		</div>
	</div>
	

	{% include 'gallery/galleryConfirmDelete.html' %}

	<script type="text/javascript">
		
		function deleteButton(image_id, gallery_slug) {
			var deleteButton = document.getElementsByClassName("deleteButton");
			var url = "{% url 'gallerys:image-delete' 0 999 %}";

			url = url.replace('0', gallery_slug);
			url = url.replace('999', image_id);
			deleteButton[0].href = url;
			deleteButton[1].href = url;
		}

	</script>

{% endblock %}

templates/gallery/gallery_detail.html
{% extends 'userProfile/base.html' %}
{% load staticfiles %}
{% block title %}{{ user }} Gallery Images{% endblock %}
{% block gallery_active %}active{% endblock %}

{% block profile_content %}
	<div id="grey-overlay"></div> 
	<div id="detailImageContainer" class="col-md-12 col-sm-12 col-xs-12">
		<div class="row">
			<div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-offset-1 col-xs-10">
				<div class="thumbnail" id="imageDetailThumbnail" style="height: auto;">
					<div class="btn btn-default btn-xs hidden-sm hidden-md hidden-lg" onclick="closeImage();" href=""><span class="glyphicon glyphicon-remove"></span></div>
					<div class="btn btn-default hidden-xs" onclick="closeImage();" href=""><span class="glyphicon glyphicon-remove"></span></div>
					<img style="opacity: 1;" id="imgContainer" src="">
					<div class="caption">
						<a class="deleteButton" href="">
							<div class="btn btn-default btn-xs hidden-sm hidden-md hidden-lg">
								<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
							</div>
						</a>
						<a class="deleteButton" href="">
							<div class="btn btn-default hidden-xs">
								<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
							</div>
						</a>
						<h2 id="imgContainerTitle"></h2>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="container-fluid" style="margin-top: 30px;">
		{% if gallery.user == request.user %}
			<div class="row" style="margin-bottom: 30px;">
				<div class="col-md-1 col-md-offset-10">
					{% if gallery %}
						<div>
							<a href="{% url 'gallerys:image-add' user gallery.slug %}">
								<button class="btn btn-default">
									<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
								</button>
							</a>
						</div>
					{% endif %}
				</div>
			</div>
		{% endif %}
		<div class="row">
		<div class="col-md-1"></div>
			<div class="col-xs-12 col-sm-4 col-md-2">
				{% if gallery %}
					<div class="thumbnail">
					 	<img style="height: auto;" src="{{ gallery.gallery_image.url }}" alt="...">
					 	<div class="caption">
			        		

			        		<h3 class="obj-title">{{ gallery.gallery_title|title }}</h3>
			        		<p class="obj-date">{{ gallery.gallery_date }}</p>
			        		<p class="obj-desc">{{ gallery.gallery_description }}</p>
							

							{% if gallery.user == request.user %}
								<p>	
									{% if user.is_superuser %}
										{% if gallery.is_favorite %}
											<a href="{% url 'gallerys:favorite' user gallery.slug %}">
												<button class="btn btn-default">
													<span class="glyphicon glyphicon-star" aria-hidden="true"></span>
												</button>
											</a>
										{% else %}
											<a href="{% url 'gallerys:favorite' user gallery.slug %}">
												<button class="btn btn-default">
													<span class="glyphicon glyphicon-star-empty" aria-hidden="true"></span>
												</button>
											</a>
										{% endif %}
									{% endif %}
									<a href="{% url 'gallerys:gallery-update' user gallery.slug %}">
										<button class="btn btn-default">
											<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
										</button>
									</a>
									<a>
										<button class="btn btn-default" onClick='confirmDelete("{{ gallery.gallery_title }}", "gallerys:gallery-delete", "{{ gallery.user }}", "{{ gallery.slug }}")'>
											<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
										</button>
									</a>
								</p>
							{% endif %}
			      		</div>
			      	</div>
					{% else %}
						<h3>No gallery!</h3>
				{% endif %}
			</div>
			<div class="col-md-9 col-sm-8 col-xs-12">
				{% if gallery.image_set.all %}
					<div class="row row-fix">
					{% for image in gallery.image_set.all %}
						<div class="col-xs-6 col-sm-6 col-md-3">
							<div onclick='viewImage(this, "{{ image.image_title }}"); deleteButton("{{ user }}", "{{ image.id }}", "{{ gallery.slug }}");' class="thumbnail">
						 		<img class="detailimg" src="{{ image.image_image.url }}" alt="..." style="width: auto;">
					      	</div>
						</div>
						{% cycle "" "" "" "</div><div class='row row-fix'>" %}
					{% endfor %}
				{% else %}
					<h3>No images added yet!</h3>
				{% endif %}
			</div>
		</div>
	</div>
	



	<script type="text/javascript">
		
		function deleteButton(user, image_id, gallery_slug) {
			var deleteButton = document.getElementsByClassName("deleteButton");
			var url = "{% url 'gallerys:image-delete' user 0 999 %}";

			url = url.replace('user', user);
			url = url.replace('0', gallery_slug);
			url = url.replace('999', image_id);
			deleteButton[0].href = url;
			deleteButton[1].href = url;
		}

	</script>

{% endblock %}

templates/gallery/index.html
{% extends 'userProfile/base.html' %}
{% load staticfiles %}
{% block title %}{{ user|title }} Gallery Page{% endblock %}
{% block gallery_active %}active{% endblock %}

{% block profile_content %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-2 col-md-offset-10">
				{% if user.id == request.user.id %}
					<a href="{% url 'gallerys:gallery-add' user %}">
						<button class="btn btn-default">
							<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
						</button>
					</a>
				{% endif %}
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			{% include 'gallery/all_gallery.html' %}
		</div>
	</div>
{% endblock %}


  
   
      
      
    
  

templates/gallery/noFeatured.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Featured Page{% endblock %}
{% block featured_active %}active{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<h1>Featured Gallery's</h1>
		<div class="col-sm-6 col-md-4">
		<h3>No featured gallery's</h3>
		</div>
	</div>	
</div>	
{% endblock %}