KicksTV/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from .forms import UserProfileRegistrationForm

from . import views
import gallery
import kickstvDropbox
import blog
import userProfile




urlpatterns = [
    # Home Page Url
    url(r'^$', views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    
    # Dropbox Urls
    url(r'^dropbox/', include('kickstvDropbox.urls', namespace='dropbox')),
    
    # Blog Urls
    url(r'^(?P<user>[\w-]+)/blog/', include('blog.urls', namespace='blogs')),
    
    # UserProfile Urls
    url(r'^(?P<user>[\w-]+)/profile/', include('userProfile.urls', namespace='profile')),
    
    # Gallery Urls
    url(r'^(?P<gallery_user>[\w-]+)/gallery/', include('gallery.urls', namespace='gallerys')),
    url(r'^featured/gallerys$', gallery.views.featuredGallery, name='featured-gallery'),
    url(r'^search/gallerys', gallery.views.searchGallery, name='search-gallery'),
	url(r'^search/gallery/result$', gallery.views.GallerySearchListView.as_view(), name='gallery-search-list-view'),

    # Custom Registration Redux Registration 
    url(r'^accounts/register$', views.MyRegistrationView.as_view(), name="registration_register"),

    # Registration Redux Urls
    url(r'^accounts/', include('registration.backends.default.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    
    url(r'^view/(?P<slug>[\w-]+)/$', views.projectDetailView, name="project-detail"),
    url(r'^add/$', views.projectAddView, name="project-add"),
    url(r'^view/(?P<slug>[\w-]+)/delete/$', views.projectDeleteView, name="project-delete"),
    url(r'^view/(?P<slug>[\w-]+)/edit/$', views.projectEditView, name="project-edit"),


    url(r'^view/(?P<slug>[\w-]+)/post/(?P<post_id>[0-9]+)/$', views.blogDetailView, name="post-detail"),
    url(r'^view/(?P<slug>[\w-]+)/post/add/$', views.blogAddView, name="post-add"),
    url(r'^view/(?P<slug>[\w-]+)/post/(?P<post_id>[0-9]+)/delete/$', views.blogDeleteView, name="post-delete"),
    url(r'^view/(?P<slug>[\w-]+)/post/(?P<post_id>[0-9]+)/edit/$', views.blogEditView, name="post-edit"),
]

blog/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import Permission, User
from django.conf import settings

from django.urls import reverse
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.db import models

import os
import sys
import shutil



# Create your models here.

def upload_location(instance, filename):
    folder = instance.slug.replace("_", "/")
    return "project_images/%s/%s" %(folder, filename)


class Project(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, related_name="project_set", on_delete=models.CASCADE)
	name = models.CharField(max_length=60)
	image = models.FileField(upload_to=upload_location, 
		null=False, 
		blank=False,)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	slug = models.SlugField(max_length=60, unique=True)
	on_going = models.BooleanField(default=True)
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	description = models.CharField(max_length=70)

	def __unicode__(self):
		return self.name

	def __str__(self):
		return self.name

	def get_absolute_url(self):
		return reverse("blogs:project-detail", kwargs={
			"user": self.user,
			"slug": self.slug,
			})



class Post(models.Model):
	project = models.ForeignKey(Project, on_delete=models.CASCADE)
	title = models.CharField(max_length=60)
	content = models.TextField()
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	draft = models.BooleanField(default=True)
	publish = models.DateField(auto_now=False, auto_now_add=False)

	def __unicode__(self):
		return self.title

	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse("blogs:post-detail", kwargs={
			"user": self.project.user,
			"slug": self.project.slug,
			"post_id": self.id,
			})



def create_slug(instance, new_slug=None):
	slug = "%s_%s" %(instance.user, slugify(instance.name))
	
	if new_slug is not None:
		slug = new_slug

	qs = Project.objects.filter(slug=slug).order_by("-id")
	exists = qs.exists()
	if exists:
		new_slug = "%s_%s-%s" %(instance.user, slugify(instance.name),qs.first().id)
		return create_slug(instance, new_slug=new_slug)
	return slug


def pre_save_project_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = create_slug(instance)


pre_save.connect(pre_save_project_receiver, sender=Project)

@receiver(models.signals.post_delete, sender=Project)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.image:
        if os.path.isfile(instance.image.path):
            print(instance.image.path)
            os.remove(instance.image.path)
            try:
                folder = instance.image.path.rsplit('/', 1)
                shutil.rmtree(folder[0])
            except OSError, e:
                print("Error: %s - %s." % (e.filename, e.strerror))

blog/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Post, Project


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'draft', 'publish', 'content']


class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['name', 'image', 'on_going', 'description']

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import Permission, User
from django.http import HttpResponseRedirect, HttpResponse
from django.utils.datastructures import MultiValueDictKeyError
from django.urls import reverse
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Post, Project
from .forms import PostForm, ProjectForm

IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']
# Create your views here.

def index(request, user):
	user = User.objects.get(username=user)
	all_projects = Project.objects.filter(user=user).order_by("-timestamp")
	
	
	paginator = Paginator(all_projects, 6) # Show 25 contacts per page

	page = request.GET.get('page')
	try:
		project = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		project = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		project = paginator.page(paginator.num_pages)


	context = {
		'all_projects': project,
		'user': user,
	}
	return render(request, 'blog/index.html', context)

def projectDetailView(request, user, slug):
	user = get_object_or_404(User, username=user)
	project = get_object_or_404(Project, slug=slug)
	all_posts = Post.objects.filter(project=project).order_by("-publish")

	paginator = Paginator(all_posts, 10) # Show 25 contacts per page

	page = request.GET.get('page')
	try:
		post = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		post = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		post = paginator.page(paginator.num_pages)

	context = {
		'project': project,
		'all_posts': post,
		'user': user,
	}
	return render(request, 'blog/projectDetail.html', context)

def projectAddView(request, user):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/accounts/login')
	else:
		user = get_object_or_404(User, username=user)
		form = ProjectForm(request.POST or None, request.FILES or None)
		if form.is_valid():
		    newProject = form.save(commit=False)
		    newProject.image = request.FILES['image']
		    file_type = newProject.image.url.split('.')[-1]
		    file_type = file_type.lower()
		    if file_type not in IMAGE_FILE_TYPES:
		        context = {
		            'formTitle': 'Create Project',
		            'newProject': newProject,
		            'form': form,
		            'error_message': 'Image file must be PNG, JPG, or JPEG',
		        }
		        return render(request, 'default-form.html', context)
		    newProject.save()
		    messages.success(request, 'Successfully Created!')
		    return HttpResponseRedirect(newProject.get_absolute_url())
		context = {
		    'formTitle': 'Create Project',
		    "form": form,
		}
	return render(request, 'default-form.html', context)

def projectDeleteView(request, user, slug):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/accounts/login')
	else:
		user = get_object_or_404(User, username=user)
		project = get_object_or_404(Project, slug=slug)
		project.delete()
		messages.error(request, 'Successfully Deleted!')
		return HttpResponseRedirect(reverse('blogs:index', args=[user]))

def projectEditView(request, user, slug):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/accounts/login')
	else:
		project = get_object_or_404(Project, slug=slug)
		form = ProjectForm(request.POST or None, request.FILES or None, instance=project)
		if form.is_valid():
		    newProject = form.save(commit=False)
		    try:
			    newProject.image = request.FILES['image']
			    file_type = newProject.image.url.split('.')[-1]
			    file_type = file_type.lower()
			    if file_type not in IMAGE_FILE_TYPES:
			        context = {
			            'formTitle': 'Edit Project',
			            'newProject': newProject,
			            'form': form,
			            'error_message': 'Image file must be PNG, JPG, or JPEG',
			        }
			        return render(request, 'default-form.html', context)
		    except MultiValueDictKeyError:
		    	newProject.image = newProject.image
		    	
		    newProject.save()
		    messages.success(request, 'Successfully Eddited!')
		    return HttpResponseRedirect(newProject.get_absolute_url())
		context = {
		    'formTitle': 'Edit Project',
		    "form": form,
		}
	return render(request, 'default-form.html', context)

def blogDetailView(request, user, slug, post_id):
	user = get_object_or_404(User, username=user)
	project = get_object_or_404(Project, slug=slug)
	post = get_object_or_404(Post, pk=post_id)

	

	context = {
		'project': project,
		'post': post,
		'user': user,
	}
	return render(request, 'blog/postDetail.html', context)



def blogAddView(request, user, slug):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/accounts/login')
	else:
		form = PostForm(request.POST or None)
		project = get_object_or_404(Project, slug=slug)
		if form.is_valid():
		    newPost = form.save(commit=False)
		    newPost.project = project
		    newPost.save()
		    messages.success(request, 'Successfully Added!')
		    return HttpResponseRedirect(newPost.get_absolute_url())
		context = {
		    'formTitle': 'Create Post',
		    "form": form,
		}
	return render(request, 'default-form.html', context)



def blogDeleteView(request, user, slug, post_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/accounts/login')
	else:
		project = get_object_or_404(Project, slug=slug)
		post = get_object_or_404(Post, pk=post_id)
		post.delete()
		messages.error(request, 'Successfully Deleted!')
		return HttpResponseRedirect(project.get_absolute_url())



def blogEditView(request, user, slug, post_id):
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/accounts/login')
	else:
		post = get_object_or_404(Post, id=post_id)
		form = PostForm(request.POST or None, instance=post)
		if form.is_valid():
		    newPost = form.save(commit=False)
		    newPost.save()
		    messages.success(request, 'Successfully Eddited!')
		    return HttpResponseRedirect(newPost.get_absolute_url())
		context = {
		    'formTitle': 'Edit Post',
		    "form": form,
		}
	return render(request, 'default-form.html', context)

templates/blog/all_projects.html
{% if all_projects %}
	<div class="row row-fix">
	{% for project in all_projects %}
		<div class="col-sm-4 col-md-4">	
			<div class="thumbnail">
			 	<img src="{{ project.image.url }}" alt="Missing image for - {{ project.name }}">
			 	<div class="caption">
	        		<h3 class="obj-title">{{ project.name|title }}</h3>
	        		<p class="obj-default">By - <a href="{% url 'profile:index' project.user %}">{{ project.user|title }}</a></p>
	        		<p class="obj-date">{{ project.timestamp|timesince }}</p>
	        		<p class="obj-date">{{ project.post_set.count }} posts</p>   
	        		<p class="obj-desc">{{ project.description }}</p>
	        		<p>
	        			<a class="btn btn-primary" href="{% url 'blogs:project-detail' project.user project.slug %}">View</a>
	        		</p>
	      		</div>
			</div>
		</div>

		{% cycle "" "" "</div><div class='row row-fix'>" %}
	{% endfor %}
	</div>
	<div class="pagination">
		<span class="step-links">
		{% if all_projects.has_previous %}
			<a href="?page={{ all_projects.previous_page_number }}">previous</a>
		{% endif %}

		<span class="current">
			Page {{ all_projects.number }} of {{ all_projects.paginator.num_pages }}.
		</span>

		{% if all_projects.has_next %}
			<a href="?page={{ all_projects.next_page_number }}">next</a>
		{% endif %}
		</span>
	</div>
	{% else %}
		<h3>No projects!</h3>
{% endif %}

templates/blog/index.html
{% extends 'userProfile/base.html' %}
{% block title %}{{ user|title }} Blog Page{% endblock %}
{% block blog_active %}active{% endblock %}
{% load staticfiles %}

{% block profile_content %}
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-2 col-md-offset-10">
				{% if user.id == request.user.id %}
					<a class="btn btn-default" href="{% url 'blogs:project-add' user %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					</a>
				{% endif %}
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			{% include 'blog/all_projects.html' %}
		</div>
	</div>
{% endblock %}

templates/blog/postDetail.html
{% extends 'userProfile/base.html' %}
{% block title %}Blog Page{% endblock %}
{% block blog_active %}active{% endblock %}
{% load staticfiles %}

{% block profile_content %}
	
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-2 col-md-offset-9">
				{% if user.id == request.user.id %}

					<a class="btn btn-default" href="{% url 'blogs:post-edit' project.user project.slug post.id %}">
						<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
					</a>
					<a>
						<button onClick='confirmDelete("{{ post.title }}", "blogs:post-delete", "{{ user }}", "{{ project.slug }}", "{{ post.id }}")' class="btn btn-default">
							<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
						</button>
					</a>
				{% endif %}
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-md-10">
				{% if post %}
					<h3 class="obj-title">{{ post.title|title }}</h3>
					{% if post.draft == True %}<p class="tag"><span class="label label-warning">Draft</span></p>{% endif %}
					<p>
						Published - {{ post.publish }}<br>
						Last Update - {{ post.updated }}
					</p>
					<p class="post-content">{{ post.content|linebreaks }}</p>
				{% else %}
					<p>No content!</p>
				{% endif %}
			</div>
		</div>
	</div>
						
{% endblock %}

templates/blog/projectDetail.html
{% extends 'userProfile/base.html' %}
{% block title %}{{ user|title }} Blog Page{% endblock %}
{% block blog_active %}active{% endblock %}
{% load staticfiles %}

{% block profile_content %}

	<div class="container-fluid">
		<div class="row">
			<div class="col-md-1 col-md-offset-10">
				{% if user.id == request.user.id %}
					<a class="btn btn-default" href="{% url 'blogs:post-add' user project.slug %}">
						<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
					</a>
				{% endif%}
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-4 col-md-2 col-md-offset-1">
				{% if project %}
					<div class="thumbnail">
					 	<img src="{{ project.image.url }}" alt="Missing image for - {{ project.name }}">
					 	<div class="caption">
			        		<h3 class="obj-title no-margin">{{ project.name|title }}</h3>
			        		{% if project.on_going == True %}<p class="tag"><span class="label label-success">On-going</span></p>{% endif %}
			        		<p class="obj-date">{{ project.timestamp }}</p>
			        		<p class="obj-desc">{{ project.description }}</p>
			        		<p>
							{% if user.id == request.user.id %}
								<a class="btn btn-default" href="{% url 'blogs:project-edit' user project.slug %}">
									<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
								</a>
								<a>
									<button onClick='confirmDelete("{{ project.name }}", "blogs:project-delete", "{{ project.user }}", "{{ project.slug }}")' class="btn btn-default">
										<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
									</button>
								</a>
							{% endif %}
							</p>
			      		</div>
					</div>
					{% else %}
						<h3>No projects!</h3>
				{% endif %}
			</div>

			<div class="col-md-7 col-md-offset-1">
				{% if all_posts %}
					{% for post in all_posts %}
						<ul>
							<a class="post-link" href="{% url 'blogs:post-detail' user project.slug post.id %}"><li><h3>{{ post.title|title }} <small> - {{ post.publish }}</small></h3></li></a>
							{% if post.draft == True %}<li class="post-content"><span class="label label-warning">Draft</span></li>{% endif %}
							<li class="post-content">{{ post.content|linebreaks|truncatechars:180 }}</li>
						</ul>
					<hr WIDTH=90% ALIGN=CENTER>
					{% endfor %}

					<div class="pagination">
						<span class="step-links">
							{% if all_posts.has_previous %}
								<a href="?page={{ all_posts.previous_page_number }}">previous</a>
							{% endif %}

							<span class="current">
								Page {{ all_posts.number }} of {{ all_posts.paginator.num_pages }}.
							</span>

							{% if all_posts.has_next %}
								<a href="?page={{ all_posts.next_page_number }}">next</a>
							{% endif %}
						</span>
					</div>
				{% else %}
					<h3>No posts!</h3>
				{% endif %}
			</div>

		</div>
	</div>



								

	
{% endblock %}