KicksTV/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from .forms import UserProfileRegistrationForm

from . import views
import gallery
import kickstvDropbox
import blog
import userProfile




urlpatterns = [
    # Home Page Url
    url(r'^$', views.index, name="index"),
    url(r'^admin/', admin.site.urls),
    
    # Dropbox Urls
    url(r'^dropbox/', include('kickstvDropbox.urls', namespace='dropbox')),
    
    # Blog Urls
    url(r'^(?P<user>[\w-]+)/blog/', include('blog.urls', namespace='blogs')),
    
    # UserProfile Urls
    url(r'^(?P<user>[\w-]+)/profile/', include('userProfile.urls', namespace='profile')),
    
    # Gallery Urls
    url(r'^(?P<gallery_user>[\w-]+)/gallery/', include('gallery.urls', namespace='gallerys')),
    url(r'^featured/gallerys$', gallery.views.featuredGallery, name='featured-gallery'),
    url(r'^search/gallerys', gallery.views.searchGallery, name='search-gallery'),
	url(r'^search/gallery/result$', gallery.views.GallerySearchListView.as_view(), name='gallery-search-list-view'),

    # Custom Registration Redux Registration 
    url(r'^accounts/register$', views.MyRegistrationView.as_view(), name="registration_register"),

    # Registration Redux Urls
    url(r'^accounts/', include('registration.backends.default.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    
    url(r'^view/(?P<slug>[\w-]+)/$', views.projectDetailView, name="project-detail"),
    url(r'^add/$', views.projectAddView, name="project-add"),
    url(r'^view/(?P<slug>[\w-]+)/delete/$', views.projectDeleteView, name="project-delete"),
    url(r'^view/(?P<slug>[\w-]+)/edit/$', views.projectEditView, name="project-edit"),


    url(r'^view/(?P<slug>[\w-]+)/post/(?P<post_id>[0-9]+)/$', views.blogDetailView, name="post-detail"),
    url(r'^view/(?P<slug>[\w-]+)/post/add/$', views.blogAddView, name="post-add"),
    url(r'^view/(?P<slug>[\w-]+)/post/(?P<post_id>[0-9]+)/delete/$', views.blogDeleteView, name="post-delete"),
    url(r'^view/(?P<slug>[\w-]+)/post/(?P<post_id>[0-9]+)/edit/$', views.blogEditView, name="post-edit"),
]

gallery/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import Permission, User
from django.db import models
from django.core.urlresolvers import reverse
from django.dispatch import receiver
from django.db.models.signals import pre_save
from django.shortcuts import get_object_or_404

from django.utils.text import slugify


import os
import sys
import shutil

 
# Create your models here.
def upload_location(instance, filename):
    folder = instance.slug.replace("_", "/")
    return "gallery_images/%s/%s" %(folder, filename)

class Gallery(models.Model):
    user = models.ForeignKey(User, default=1)
    gallery_title = models.CharField(max_length=25)
    gallery_date = models.DateField(null=False, blank=False)
    gallery_image = models.ImageField(
        upload_to=upload_location, 
        null=False, 
        blank=False,
        height_field="height_field",
        width_field="width_field",
        )
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    slug = models.SlugField(max_length=40, unique=True)
    gallery_description = models.CharField(max_length=70)
    is_favorite = models.BooleanField(default=False)
    is_homepage_gallery = models.BooleanField(default=False)

    def __unicode__(self):
        return self.gallery_title

    def __str__(self):
        return self.gallery_title

    def get_absolute_url(self):
        return reverse("gallerys:user-gallery-detail", kwargs={
            "slug": self.slug,
            "gallery_user": self.user,
            })

class Image(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    image_title = models.CharField(max_length=25)
    image_image = models.ImageField(
        upload_to=upload_location,
        height_field="height_field",
        width_field="width_field",
        )
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    slug = models.SlugField(max_length=40)

    def __unicode__(self):
        return self.image_title

    def __str__(self):
        return self.image_title



# Creating slugs before saving
def create_slug(instance, new_slug=None):
    slug = "%s_%s" %(instance.user, slugify(instance.gallery_title))
    if new_slug is not None:
        slug = new_slug
    qs = Gallery.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s_%s-%s" %(instance.user, slugify(instance.gallery_title),qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_gallery_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    elif not instance.slug == slugify(instance.user) + "" + slugify(instance.gallery_title): 
        instance.slug = create_slug(instance)

def pre_save_image_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        gallery = Gallery.objects.get(id=instance.gallery.id)
        instance.slug = "%s_%s" %(gallery.user,slugify(gallery.gallery_title))


# These two auto-delete files from filesystem when they are unneeded:

@receiver(models.signals.post_delete, sender=Gallery)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.gallery_image:
        if os.path.isfile(instance.gallery_image.path):
            os.remove(instance.gallery_image.path)
            try:
                folder = instance.gallery_image.path.rsplit('/', 1)
                shutil.rmtree(folder[0])
            except OSError, e:
                print("Error: %s - %s." % (e.filename, e.strerror))


def auto_delete_file_on_change(sender, instance, *args, **kwargs):
    """
    Deletes old file from filesystem
    when corresponding `MediaFile` object is updated
    with new file.
    """
    if not instance.pk:
        print("instance.pk is null")
        return

    if instance.gallery_title:
        old_gallery = get_object_or_404(Gallery, id=instance.pk)
        if instance.gallery_title == old_gallery.gallery_title:
            return

    gallery_path = str(instance.gallery_image).split("/")
    old_file = gallery_path[1] + "/" + gallery_path[2]
    new_file = instance.slug.replace("_", "/")
    
    if not old_file == new_file:
        folder_path_to_change = str(instance.gallery_image.path).rsplit('/', 1)
        folder_path = str(instance.gallery_image.path).rsplit('/', 2)
        new_folder_name = str(new_file).rsplit('/', 1)
        os.rename(folder_path_to_change[0], folder_path[0] + "/" + new_folder_name[1])
        instance.gallery_image = gallery_path[0] + "/" + gallery_path[1] + "/" + new_folder_name[1] + "/" + gallery_path[3]

        all_images = Image.objects.filter(gallery=instance)
        if all_images:
            for image in all_images:
                if not os.path.isfile(image.image_image.path):
                    image_path = str(image.image_image).split("/")
                    print(image_path[0] + "/" + image_path[1] + "/" + new_folder_name[1] + "/" + image_path[3])
                    image.image_image = image_path[0] + "/" + image_path[1] + "/" + new_folder_name[1] + "/" + image_path[3]
                    image.save()


pre_save.connect(pre_save_gallery_receiver, sender=Gallery)
pre_save.connect(pre_save_image_receiver, sender=Image)
pre_save.connect(auto_delete_file_on_change, sender=Gallery)

templates/ConfirmDelete.html
<div id="whiteContainer" style="display: none;">
	<div id="confirmDeleteContainer" style="display: none;">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 id="confirmDeleteTitle" class="panel-title" style="display: inline-block;"></h3>
			</div>
			<div class="panel-body">
				<div class="col-md-12">
					<p>Do you want to delete the following object?</p><br>
					<div class="btn-group" role="group" aria-label="...">
						<button onClick="cancelDelete()" class="btn btn-default">
							Cancel
						</button>
						<a id="deleteURL" href="">
							<button  class="btn btn-danger">
									Delete
							</button>
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
function confirmDelete(title, url, user, slug, post_id) {
	var container = document.getElementById("confirmDeleteContainer");
	var containerTitle = document.getElementById("confirmDeleteTitle");
	var whiteContainer = document.getElementById("whiteContainer");
	var deleteURL = document.getElementById("deleteURL");



	whiteContainer.style.display = "block";
	whiteContainer.style.zIndex = "5000";

	if (url == "gallerys:gallery-delete") {
		var url = "{% url 'gallerys:gallery-delete' 0 99 %}";
		url = url.replace('0', user);
		url = url.replace('99', slug);

	}
	else if (url == "blogs:project-delete") {
		var url = "{% url 'blogs:project-delete' 0 99 %}";
		url = url.replace('0', user);
		url = url.replace('99', slug);
	}
	else if (url == "blogs:post-delete") {
		var url = "{% url 'blogs:post-delete' 0 99 88 %}";
		url = url.replace('0', user);
		url = url.replace('99', slug);
		url = url.replace('88', post_id);
	}


	deleteURL.href = url;


	containerTitle.innerHTML = title;
	container.style.display = "block";
}
</script>

templates/base.html
{% load staticfiles %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
		<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
		<meta name="description" content="">
		<meta name="author" content="">
		<!--<link rel="icon" href="../../favicon.ico"> -->

		<title>{% block title %}{% endblock %}</title>

		<!-- Bootstrap core CSS -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />
		<!-- Icons -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous" />
		
		<!-- FONTS -->
		<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Lobster" />
		<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Raleway:700" rel="stylesheet" />

		<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
		<link rel="stylesheet" type="text/css" href="{% static 'css/ie10-viewport-bug-workaround.css' %}" />

		<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />

		<!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
		<!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
		<script src="{% static 'js/ie-emulation-modes-warning.js' %}"></script>

		<!-- Captcha -->
		<script src='https://www.google.com/recaptcha/api.js'></script>
	</head>

	<body>
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a href="{% url 'index' %}" style="color: #7066ff;" class="navbar-brand">Kicks</a>
					<a href="{% url 'index' %}" style="font-family: 'Raleway', sans-serif; padding: 15px 15px 15px 0; color: #7066ff;" class="navbar-brand">TV</a>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Gallery's&nbsp;<span class="caret"></span></a>
								<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
									<li class="{% block featured_active %}{% endblock %}"><a href="{% url 'featured-gallery' %}">Featured Gallery's</a></li>
									<li class="{% block search_active %}{% endblock %}"><a href="{% url 'search-gallery' %}">Search Gallery's</a></li>
								</ul>
							</li>
						<li class="{% block blog_active %}{% endblock %}"><a href="{% url 'blogs:index' 'kickstv' %}">Blog</a></li>
						<li class="{% block dropbox_active %}{% endblock %}"><a href="{% url 'dropbox:index' %}">Dropbox</a></li>
					</ul>
					{% if request.user.is_authenticated %}
						<ul class="nav navbar-nav navbar-right">
							<li class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.user|title }}&nbsp;<span class="caret"></span></a>
								<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
									<li class="{% block user_active %}{% endblock %}"><a href="{% url 'profile:index' request.user %}">Profile</a></li>
									<li role="separator" class="divider"></li>
									<li><a href="{% url 'auth_password_change' %}">Change Password</a></li>
									<li role="separator" class="divider"></li>
									{% if request.user.is_superuser %}
										<li><a href="{% url 'admin:index' %}">Admin</a></li>
									{% endif %}
									<li><a href="{% url 'auth_logout' %}">Logout</a></li>
								</ul>
							</li>
						</ul>
					{% else %}
						<ul class="nav navbar-nav navbar-right">
							<li class="{% block login_active %}{% endblock %}"><a href="{% url 'auth_login' %}">Login/Sign up</a></li>
						</ul>
					{% endif %}
				</div><!--/.nav-collapse -->
			</div>
		</nav>
			{% block content %}
			{% endblock %}  

			{% include 'messages.html' %}
			{% include 'ConfirmDelete.html' %}
	<!-- Bootstrap core JavaScript
		================================================== -->
		<!-- Placed at the end of the document so the pages load faster -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
		<script src="{% static 'js/bootstrap.min.js' %}"></script>
		<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
		<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
		<script type="text/javascript" src="{% static 'js/main.js' %}"></script>
	</body>
</html>

templates/default-form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}Add New Gallery{% endblock %}
{% block gallery_active %}active{% endblock %}

{% block content %}
	<div class="container" style="margin-top: 50px;">
		<div class="row">
			<div class="col-sm-12 col-md-offset-3 col-md-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title" style="display: inline-block;">
							{% if formTitle %}
								{{ formTitle|title }}
								{% else %}
									Error: no title
							{% endif %}
						</h3>
					</div>
					<div class="panel-body">
						<form action="" method="post" enctype="multipart/form-data">
						{% csrf_token %}
							{{ form|crispy }}		
							<button type="submit" class="btn btn-success">Submit</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

templates/form-template.html
{% for field in form %}
	<div class="col-sm-offset-2 col-sm-10">
		<span class="text-danger small">{{ field.errors }}</span>
	</div>

	<div style="margin-bottom: 20px;" class="input-group">
		{{ field.label_tag }}
		{{ field }}
	</div>
{% endfor %}

templates/index.html
{% extends 'base.html' %}
{% block title %}Home Page{% endblock %}
{% block home_active %}active{% endblock %}
{% load staticfiles %}

{% block content %}
	<div class="container-fluid home-page-gallery">
		<div id="imgConHome" class="col-md-12" style="opacity: 0;">
			<div class="row" style="height: 100%;">
				<div class="arrowContainer-left col-sm-1 col-xs-2" style="white-space: nowrap;height: 100%;">
					<span class="helper"></span><img class="Arrow" src="{% static 'img/back.svg' %}" onClick="preImage()">
				</div>
				<div class="col-md-10 col-sm-10 col-xs-8"></div>
				<div class="arrowContainer-right col-sm-1 col-xs-2" style="white-space: nowrap;height: 100%;">
					<span class="helper"></span><img class="Arrow" src="{% static 'img/next.svg' %}" onClick="nextImage()">
				</div>
			</div>
		</div>
	</div>
	<div class="container" style="height: 550px;">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title" style="display: inline-block;">Blog</h3>
				</div>
				<div class="panel-body">
					<div class="col-md-12">
						{% include 'blog/all_projects.html' %}
					</div>
				</div>
			</div>
		</div>
	</div>

		<!-- <div class="col-md-2">
			<div class="panel panel-success">
				<div class="panel-heading">MC Server</div>
				<div class="panel-body">
					<div class="col-md-6">
						<p>
							{% if hostname %}
								{{ hostname }}
							{% else %}
								Error
							{% endif %}
						</p>
					</div>
					<div class="col-md-6" style="height: 30px">
						<h4 style="margin-top: 0px;">
							{% if serverStatus == "success" %}
							<span class="label label-success" style="float: right;">Online</span>
							{% else %}
							<span class="label label-danger" style="float: right;">Offline</span>
							{% endif %}
						</h4>
					</div>
					<div class="col-md-6"><p>Players</p></div>
					<div class="col-md-6"><p style="float: right;">{{ onlinePlayers }}/{{ maxPlayers }}</p></div>
				</div>
			</div>
			<div class="panel panel-success">
				<div class="panel-heading">Player List</div>
				<div style="overflow-y: scroll; height: 300px;">
					{% if list %}
						{% for player in list %}
							<div class="panel-body">
								{{ player }}
							</div>
						{% endfor %}
					{% else %}
						<div class="panel-body">
							Error: no players
						</div>
					{% endif %}
				</div>
			</div>
		</div> -->
		

		<!-- <div class="col-md-2" >
			<iframe style="float:right;" src="https://discordapp.com/widget?id=355323843046539264&theme=dark" width="300" height="500" allowtransparency="true" frameborder="0"></iframe>
		</div>	 -->	
	
	
	{% if desktop_gallery %}
	<script type="text/javascript">
		var preImageContainer = document.getElementById("preImageContainer");
		var nextImageContainer = document.getElementById("nextImageContainer");
		

		var imgN = 0;
		var imgConHome = document.getElementById("imgConHome");
		var myDesktopGallery = new Object();
		var myMobileGallery = new Object();
		var allImages = [];
		var i = 0;
		var opc = 0;

		var fadeOutTimer;
		var fadeInTimer;

		{% for image in desktop_gallery.image_set.all %}
			myDesktopGallery.image{{ image.id }} = {
				file_path: "{{ image.image_image.url }}"
			};
		{% endfor %}

		{% for image in mobile_gallery.image_set.all %}
			myMobileGallery.image{{ image.id }} = {
				file_path: "{{ image.image_image.url }}"
			};
		{% endfor %}


		if (window.screen.width >= 767) {
			for (images in myDesktopGallery) {
				allImages[i] = myDesktopGallery[images].file_path;
				i +=1
			}
		}

		if (window.screen.width <= 479) {
			for (images in myMobileGallery) {
				allImages[i] = myMobileGallery[images].file_path;
				i +=1
			}
		}


		function fadeImageOut() {			
			if (imgConHome.style.opacity <= 0) {
				console.log("stopping fadding");
				clearInterval(fadeOutTimer);
				setTimeout(setImage, 1500);
			}
			else {
				console.log("fading");
				imgConHome.style.opacity = opc;
				opc -= 0.05;	
			}
		}

		function fadeImageIn() {			
			if (imgConHome.style.opacity >= 1) {
				console.log("stopping fadding");
				clearInterval(fadeInTimer);
			}
			else {
				console.log("fading");
				imgConHome.style.opacity = opc;
				opc += 0.05;		
			}
		}

		function setImage() {
			if (imgN >= allImages.length ) {
				imgN = 0;
			}
			else if (imgN < 0 ) {
				imgN = allImages.length-1;
			}
			if (imgConHome.style.opacity >= 1) {
				fadeImageOut();
				fadeOutTimer = setInterval(fadeImageOut, 50);
			}
			
			if (imgConHome.style.opacity <= 0) {
				if (window.screen.width < 767) {
					imgConHome.style.background = "url('" + allImages[imgN] + "')";
					imgConHome.style.backgroundSize = "100% 100%";
					imgConHome.style.backgroundRepeat = "no-repeat";
					imgConHome.style.backgroundAttachment = "fixed";
					imgConHome.style.backgroundPosition = "center";
				}else {
					imgConHome.style.background = "url('" + allImages[imgN] + "') no-repeat center center fixed";
				}
				setTimeout(fadeInTimer = setInterval(fadeImageIn, 50), 8000);
				
			}
		}



		function nextImage() {
			imgN += 1
			clearInterval(setImageTimer);
			setImageTimer = setInterval(nextImage, 9000);
			setImage();
		}

		function preImage() {
			imgN -= 1
			clearInterval(setImageTimer);
			setImageTimer = setInterval(setImage, 9000);
			setImage();
		}


		setImage();		
		var setImageTimer = setInterval(nextImage, 9000);

		


	</script>
	{% endif %}
{% endblock %}

templates/messages.html
{% if messages %}
	<div class="messageBox col-md-4 col-md-offset-7 col-sm-4 col-sm-offset-7 col-xs-11">
	{% for message in messages %}
		{% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
			<div class="alert alert-success alert-dismissible {{ message.tags }}" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span></button>
				{{ message }}
			</div>
		{% endif %}
		{% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}<div class="alert alert-danger alert-dismissible {{ message.tags }}" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span></button>
			{{ message }}
		</div>
		{% endif %}
	{% endfor %}
	</div>
{% endif %}

templates/notMember.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Featured Page{% endblock %}
{% block featured_active %}active{% endblock %}

{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-6 col-md-4">
		<h3>You must be a member!</h3>
		</div>
	</div>	
</div>	
{% endblock %}